<?php

/**
 * @file
 * The module file for foursquare feed
 */
/**
 * Hook that calls feed module to process the feed 
 * @param string $user Contains uid, userid, password, feed entered on user's settings page
 */
function activitystream_foursquare_streamapi($user) {
  // User doesn't have a identi.ca username entered
  if (!$user->feed) {
    return;
  }
  
  // Use activitystream_feed module to pull information
  $items = activitystream_feed_streamapi($user);
  return $items;
}
/**
 * Hook for user settings form.
 * Will be added by activitystream module
 * @param array $edit Values of the form fields
 */
function activitystream_foursquare_activitystream_settings(&$edit) {
  $form['activitystream_foursquare'] = array(
    '#type' => 'fieldset',
    '#title' => t('Foursquare settings')
  );
  $form['activitystream_foursquare']['activitystream_foursquare_feed'] = array(
    '#type' => 'textfield',
    '#title' => t('Feed URL'),
    '#default_value' => empty($edit['activitystream_foursquare_feed']) ? '' : $edit['activitystream_foursquare_feed'],
    '#description' => t('Your foursquare RSS Feed URL.  Can be found ') .'<a href="http://http://foursquare.com/feeds/">here</a>'
  );
  return $form;
}
function theme_activitystream_foursquare_icon() {
  return theme_image(drupal_get_path('module', 'activitystream_foursquare') .'/fsq.jpg', 'foursquare');
}
function theme_activitystream_foursquare_item($activity) {
  $node = node_load($activity->nid);
  $date = theme('activitystream_date', $node->created);
  $user = activitystream_user_load($node->uid);
  $name = theme('activitystream_username', $user);
  return '<span class="activitystream-item">'. theme('activitystream_foursquare_icon') .' <span>'. $name .' checked in at '. l($node->title, $activity->link) .'<span class="activitystream-created">'. $date .'</span></span>'. l('#', 'node/'. $node->nid, array('class' => 'permalink')) .'</span>';
}
function activitystream_foursquare_theme() {
  return array(
    'activitystream_foursquare_icon' => array(
      'arguments' => array(),
    ),
    'activitystream_foursquare_item' => array(
      'arguments' => array('activity' => NULL),
    ),
  );
}

